### ISSUE TITLE
edit starters error - IntelliJ 2020.1

### ISSUE THREAD

**Issue by ayunas** [hdzitao/idea-editstarters-plugin#4]
please see stackoverflow post for the issue : 

[https://stackoverflow.com/questions/64933523/edit-spring-boot-starters-error-in-intellij](url)

**Comment by hdzitao** [comment]
Thinks for issue. This problem is caused by the old version，please upgrade to 2.3.0
And supported spring boot versions depend on https://start.spring.io/

**Comment by hdzitao** [comment]
But it doesn't mean 2.3.4 is not supported,  it depends on whether https://start.spring.io/ returns data
