### ISSUE TITLE
服务地址使用阿里的报错

### ISSUE THREAD

**Issue by cjp314** [hdzitao/idea-editstarters-plugin#6]
url 使用https://start.aliyun.com/,点击ok后提示request failure

**Comment by hdzitao** [comment]
使用https://start.aliyun.com/时，请求具体版本信息，如http://start.aliyun.com/dependencies?bootVersion=2.4.1可以正常返回个json，但是有一些版本，如http://start.aliyun.com/dependencies?bootVersion=2.2.13 会返回一个页面导致json解析错误。
